%\VignetteEngine{knitr::knitr}

<<setup, include=FALSE, cache=FALSE>>=
# Set options
knitr::opts_chunk$set(include=TRUE, results="hide", fig.width=8, fig.height=8, fig.path='figures/', fig.align='center', fig.show='hold',warning=FALSE, echo=FALSE, message=FALSE, cache=FALSE)
options(replace.assign=TRUE,width=90)
days.per.month <- 30.4368
days.per.year <- 365.242
par.original <- par()
library(knitr)
library(gdata)
library(annotate)
library(ggplot2)
library(xtable)
library(genefu)
library(reshape2)
library(hgu133plus2.db)
library(metafor)

survival.type <- "os"
survival.type.title <- "Overall Survival"
if(survival.type != "os") {
  survival.type.title <- "Recurrence-Free Survival"
}
@


\documentclass{article}

\usepackage{graphicx}
\usepackage{microtype}
\usepackage[T1]{fontenc}
\usepackage{float}
\usepackage[latin1]{inputenc}
\usepackage{geometry}
\usepackage{titlesec}
\usepackage{tabularx}
\geometry{verbose,tmargin=2.5cm,bmargin=2.5cm,lmargin=2.5cm,rmargin=2.5cm}
\usepackage[table]{xcolor}
\usepackage{hyperref}
\hypersetup{
    colorlinks,
    citecolor=black,
    filecolor=black,
    linkcolor=black,
    urlcolor=black
}
%\newcommand{\sectionbreak}{\clearpage}

\begin{document}

\title{Ovarian Cancer Prognosis \Sexpr{survival.type.title}}

%\author{Gregory M. Chen}
\date{\today}
\maketitle


<<load_data, cache=FALSE>>=
source(system.file("extdata", "patientselection.config", package="MetaGxOvarian"))
remove.datasets <- "TCGA.RNASeqV2"
source(system.file("extdata", "createEsetList.R", package="MetaGxOvarian"))

esets <- lapply(esets, function(x) {
  factor.indices <- sapply(pData(x), is.factor)
  pData(x)[factor.indices] <- lapply(pData(x)[factor.indices], as.character)
  return(x)
  })

eset.names <- names(esets)
esets <- lapply(names(esets), function(x) {
  eset.toreturn <- esets[[x]]
  eset.toreturn$data.source <- x
  return(eset.toreturn)
  })
names(esets) <- eset.names

gene.table <- read.table("Intersecting.genes.tsv", sep="\t", header=TRUE, stringsAsFactors = FALSE)
gene.names <- gene.table$Gene.name
entrez.ids <- gene.table$Entrez.ID

# only keep patients with survival data
esets.rfs <- lapply(esets, function(eset) eset[,!is.na(eset$recurrence_status) & !is.na(eset$days_to_tumor_recurrence)])
esets.os <- lapply(esets, function(eset) eset[,!is.na(eset$vital_status) & !is.na(eset$days_to_death)])

## Remove datasets that are empty
esets.rfs <- esets.rfs[sapply(esets.rfs, function(x) ncol(exprs(x)) > 0)]
esets.os <- esets.os[sapply(esets.os, function(x) ncol(exprs(x)) > 0)]
rm(esets)
@

\tableofcontents
\section{Datasets}

<<get_num_genes_datasets>>=
if(survival.type == "rfs") {
  num.patients <- sum(sapply(esets.rfs, function(x) ncol(exprs(x))))
  num.datasets <- length(esets.rfs)
  survival.type.text <- "recurrence-free"
} else if(survival.type == "os") {
  num.patients <- sum(sapply(esets.os, function(x) ncol(exprs(x))))
  num.datasets <- length(esets.os)
  survival.type.text <- "overall"
}
@


From MetaGxOvarian, we selected patients from studies which tracked \Sexpr{survival.type.text} survival. We identified \Sexpr{num.patients} patients from \Sexpr{num.datasets} datasets.
<<Dataset_table, results='asis'>>=
if(survival.type == "rfs") {
  data.counts <- as.data.frame(sapply(esets.rfs, function(x) ncol(exprs(x))))
  colnames(data.counts) <- "Number of samples"
  data.counts <- rbind(data.counts, sum(data.counts[,1]))
  rownames(data.counts)[nrow(data.counts)] <- "Sum"
  xtable(data.counts)
} else if(survival.type == "os") {
  data.counts <- as.data.frame(sapply(esets.os, function(x) ncol(exprs(x))))
  colnames(data.counts) <- "Number of samples"
  data.counts <- rbind(data.counts, sum(data.counts[,1]))
  rownames(data.counts)[nrow(data.counts)] <- "Sum"
  xtable(data.counts)
}
@

<<single_gene, cache=FALSE, include=FALSE>>=
knitr.text <- lapply(1:length(entrez.ids), function(current.index) knit_expand(file='ovca.single.gene.template.Rnw'))

fixed.effects.pval <- c()
fixed.effects.estimate <- c()
fixed.effects.lower <- c()
fixed.effects.upper <- c()
rma.objs <- list()

if(survival.type == "os") {
  hr.matrix <- matrix(nrow=length(gene.names), ncol=length(esets.os))
  colnames(hr.matrix) <- names(esets.os)
} else if(survival.type == "rfs") {
  hr.matrix <- matrix(nrow=length(gene.names), ncol=length(esets.rfs))
  colnames(hr.matrix) <- names(esets.rfs)
}
rownames(hr.matrix) <- gene.names

knitr.out <- knit(text=unlist(knitr.text))
@

\pagebreak
\section{Summary of Results}
<<summary_table, results='asis'>>=
summary.table <- data.frame(gene=gene.names, pval=sprintf("%.1E", fixed.effects.pval), hr.text=sprintf("%.2f [%.2f, %.2f]", fixed.effects.estimate, fixed.effects.lower, fixed.effects.upper))
colnames(summary.table) <- c("Gene Name", "P-value", "Hazard Ratio")
write.table(summary.table,file="OverallHazardRatioMetaAnalysis.Ovarian.txt")
print(xtable(summary.table),include.rownames=FALSE)
@

\pagebreak

Summary Forest Plot
<<summary_forestplot, fig.width=5, fig.height=8>>=
estimates <- sapply(rma.objs, coef)
variances <- sapply(rma.objs, vcov)

forest(estimates, variances, atransf=exp, psize=1, efac=0, slab=names(rma.objs), xlab="Hazard Ratio",xlim=c(-2,2), at=log(c(0.25,0.5,1,2,4)))
addpoly(estimates, variances, rows=length(rma.objs):1, atransf=exp, annotate=FALSE)
abline(h=0.5, lwd=1)
@

\pagebreak
%
%\Sexpr{knitr.out}
%
\end{document}